version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - misspell
  settings:
    errcheck:
      exclude-functions:
        - (io.ReadCloser).Close
        - fmt.Fprintln
        - fmt.Fprintf
